import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2";
import { sendPushNotification, WebPushError } from "npm:@mmmike/web-push/send";
import { generateVapidKeys } from "npm:@mmmike/web-push/vapid";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") || JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS") || "{}").default;
const admin = createClient(SUPABASE_URL, SERVICE_KEY);
const CORS = {"Access-Control-Allow-Origin":"https://arafat-bashir.github.io","Access-Control-Allow-Headers":"authorization, apikey, content-type, x-kiteezi-webhook-secret","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...CORS,"Content-Type":"application/json"}});
async function config(){const {data,error}=await admin.from("push_config").select("key,public_key,private_key,webhook_secret,subject,active").eq("key","default").maybeSingle();if(error)throw error;if(!data)throw new Error("Push configuration is missing.");if(data.public_key&&data.private_key)return data;const keys=await generateVapidKeys();const {data:updated,error:updateError}=await admin.from("push_config").update({public_key:keys.publicKey,private_key:keys.privateKey,updated_at:new Date().toISOString()}).eq("key","default").select("key,public_key,private_key,webhook_secret,subject,active").single();if(updateError)throw updateError;return updated;}
function validEndpoint(endpoint:string){try{const u=new URL(endpoint);return u.protocol==="https:"&&(u.hostname==="fcm.googleapis.com"||u.hostname.endsWith(".push.services.mozilla.com")||u.hostname.endsWith(".push.apple.com")||u.hostname==="updates.push.services.mozilla.com")}catch{return false}}
async function deliver(record:any){const c=await config();if(!c.active)return{delivered:0,gone:0,failed:0,disabled:true};const {data:subs,error}=await admin.from("push_subscriptions").select("id,endpoint,p256dh,auth").eq("user_id",record.recipient_user_id);if(error)throw error;const usable=(subs||[]).filter((s)=>validEndpoint(s.endpoint));const vapid={subject:c.subject,publicKey:c.public_key,privateKey:c.private_key};const url="https://arafat-bashir.github.io/kiteezi/admin/index.html?notification="+encodeURIComponent(record.id);let delivered=0,failed=0;const gone:string[]=[];for(const s of usable){try{const ok=await sendPushNotification({endpoint:s.endpoint,keys:{p256dh:s.p256dh,auth:s.auth}},{title:record.title||"Kiteezi notification",body:record.message||"You have a new Kiteezi notification.",url,tag:"kiteezi-"+record.id},vapid,{ttl:86400,urgency:"high",timeoutMs:15000});if(ok)delivered++;else gone.push(s.endpoint)}catch(e){if(e instanceof WebPushError&&(e.statusCode===404||e.statusCode===410))gone.push(s.endpoint);else{failed++;console.error("push delivery failed",{statusCode:e instanceof WebPushError?e.statusCode:undefined})}}}if(gone.length)await admin.from("push_subscriptions").delete().in("endpoint",gone);return{delivered,gone:gone.length,failed};}
async function manualSend(req:Request,body:any){const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"").trim();if(!token)return json({error:"Authentication required."},401);const {data:au,error:ae}=await admin.auth.getUser(token);if(ae||!au?.user?.id)return json({error:"Authentication required."},401);const {data:sender,error:pe}=await admin.from("profiles").select("id,role,active,organization_id").eq("id",au.user.id).maybeSingle();if(pe||!sender?.active)return json({error:"Active staff profile required."},403);const allowed=new Set(["owner","manager","general_manager","ceo","cfo","finance_manager","reception_manager"]);if(!allowed.has(String(sender.role||"").toLowerCase()))return json({error:"You do not have permission to send staff notifications."},403);const requested=[...new Set((body?.recipient_user_ids||[]).map(String).filter(Boolean))];if(!requested.length)return json({error:"At least one recipient is required."},400);const {data:recipients,error:recipientError}=await admin.from("profiles").select("id").in("id",requested).eq("active",true).eq("organization_id",sender.organization_id);if(recipientError)throw recipientError;const ids=(recipients||[]).map((x)=>x.id);if(!ids.length)return json({error:"No active recipients in your organization matched that target."},400);const title=String(body?.title||"").trim().slice(0,160),message=String(body?.message||"").trim().slice(0,2000);if(!title||!message)return json({error:"Title and message are required."},400);const {data,error}=await admin.from("notifications").insert(ids.map((recipient_user_id:string)=>({recipient_user_id,type:"manual",title,message,reference_type:body?.reference_type?String(body.reference_type).slice(0,80):null,reference_id:body?.reference_id?String(body.reference_id):null}))).select("id,recipient_user_id");if(error)return json({error:error.message},400);return json({ok:true,count:data?.length||0,notifications:data||[]});}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response(null,{status:204,headers:CORS});try{if(req.method==="GET")return json({publicKey:(await config()).public_key,supported:true});if(req.method!=="POST")return json({error:"Method not allowed"},405);const body=await req.json().catch(()=>({}));if(body?.action==="send")return await manualSend(req,body);const c=await config();if((req.headers.get("x-kiteezi-webhook-secret")||"")!==c.webhook_secret)return json({error:"Unauthorized"},401);if(body?.type!=="INSERT"||body?.table!=="notifications")return json({ok:true,ignored:true});const record=body.record;if(!record?.id||!record?.recipient_user_id)return json({error:"Invalid notification record"},400);return json({ok:true,notification_id:record.id,...(await deliver(record))});}catch(e){console.error("kiteezi-push error",e);return json({error:e instanceof Error?e.message:"Push failed"},500)}});
