'use strict';
const C=window.KITEEZI_CONFIG||{}, URL=String(C.SUPABASE_URL||'').replace(/\/+$/,''), KEY=String(C.SUPABASE_ANON_KEY||'');
let session=null,profile=null,tab='dashboard';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('en-UG').format(Number(v)||0);
async function api(path,opt={},token=session?.access_token||KEY){const h={apikey:KEY,Authorization:'Bearer '+token,'Content-Type':'application/json',...(opt.headers||{})};if(opt.method&&opt.method!=='GET')h.Prefer='return=representation';const r=await fetch(URL+path,{...opt,headers:h});const t=await r.text();let d;try{d=t?JSON.parse(t):null}catch{d=t}if(!r.ok)throw Error(d?.message||d?.msg||d?.error_description||d?.error||(typeof d==='string'?d:'Request failed'));return d}
function msg(e){console.error(e);alert(e.message||'Something went wrong.')}
async function login(e){
  e.preventDefault();
  const f=new FormData(e.currentTarget);
  const email=String(f.get('email')||'').trim();
  const password=String(f.get('password')||'');
  const statusEl=$('#loginMsg');
  const submitBtn=e.currentTarget.querySelector('button[type="submit"]');
  statusEl.hidden=false;
  statusEl.textContent='Signing in…';
  if(submitBtn) submitBtn.disabled=true;
  try{
    if(!URL||!KEY) throw Error('Admin configuration is missing.');
    const response=await fetch(URL+'/auth/v1/token?grant_type=password',{
      method:'POST',
      headers:{apikey:KEY,'Content-Type':'application/json'},
      body:JSON.stringify({email,password})
    });
    const raw=await response.text();
    let data=null; try{data=raw?JSON.parse(raw):null}catch{}
    if(!response.ok) throw Error(data?.msg||data?.message||data?.error_description||'Invalid email or password.');
    if(!data?.access_token||!data?.user?.id) throw Error('Login succeeded but no valid session was returned.');
    session=data;
    const p=await api('/rest/v1/profiles?select=*&id=eq.'+encodeURIComponent(session.user.id)+'&limit=1');
    profile=p?.[0];
    if(!profile) throw Error('This account has no Kiteezi staff profile.');
    if(!profile.active) throw Error('This Kiteezi staff profile is inactive.');
    sessionStorage.setItem('kiteezi_admin_session',JSON.stringify(session));
    show();
  }catch(err){
    session=null; profile=null;
    statusEl.textContent=err?.message||'Sign in failed. Please try again.';
    statusEl.hidden=false;
  } finally {
    if(submitBtn) submitBtn.disabled=false;
  }
}
async function restore(){try{session=JSON.parse(sessionStorage.getItem('kiteezi_admin_session')||'null');if(!session?.access_token)throw Error();const p=await api('/rest/v1/profiles?select=*&id=eq.'+encodeURIComponent(session.user.id)+'&limit=1');profile=p?.[0];if(!profile?.active)throw Error();show()}catch{session=null;$('#loginView').classList.remove('hide')}}
function show(){$('#loginView').classList.add('hide');$('#app').classList.remove('hide');$('#who').textContent=(profile.full_name||'Staff')+' · '+profile.role;$('#rolePill').textContent=profile.role;route(location.hash.slice(1)||'dashboard')}
function route(x){tab=x||'dashboard';$$('[data-tab]').forEach(a=>a.classList.toggle('active',a.dataset.tab===tab));$$('.tab').forEach(s=>s.classList.toggle('active',s.id===tab));const f={dashboard:loadDashboard,bookings:loadBookings,restaurant:loadOrders,inventory:loadInventory,menu:loadMenu,services:loadServices,content:loadContent,reviews:loadReviews,social:loadSocial,staff:loadStaff,reports:loadReport,settings:loadSettings};(f[tab]||loadDashboard)().catch(msg)}
async function loadDashboard(){const d=today();const [b,o,i]=await Promise.all([api('/rest/v1/bookings?select=id,status&booking_date=eq.'+d),api('/rest/v1/orders?select=id,status&status=not.eq.completed&status=not.eq.cancelled'),api('/rest/v1/inventory_items?select=id,reorder_level')]);const sm=await api('/rest/v1/stock_movements?select=item_id,quantity,movement_type');const stock={};sm.forEach(x=>stock[x.item_id]=(stock[x.item_id]||0)+(String(x.movement_type).toLowerCase()==='out'?-1:1)*Number(x.quantity||0));$('#mBookings').textContent=b.length;$('#mPending').textContent=b.filter(x=>x.status==='pending').length;$('#mOrders').textContent=o.length;$('#mLow').textContent=i.filter(x=>(stock[x.id]||0)<=Number(x.reorder_level||0)).length;$('#todayOps').textContent='Live data connected.'}
function today(){return new Date().toISOString().slice(0,10)}
async function loadBookings(){const filter=$('#bookingFilter').value;let q='/rest/v1/bookings?select=*,customers(name,phone)&order=booking_date.desc,start_time.asc';if(filter!=='all')q+='&status=eq.'+filter;const rows=await api(q);$('#bookingTable').innerHTML=rows.length?'<table><tr><th>Date</th><th>Customer</th><th>People</th><th>Total</th><th>Status</th><th></th></tr>'+rows.map(r=>'<tr><td>'+esc(r.booking_date)+' '+esc(r.start_time||'')+'</td><td>'+esc(r.customers?.name||'')+'<br>'+esc(r.customers?.phone||'')+'</td><td>'+r.people+'</td><td>UGX '+money(r.total)+'</td><td>'+esc(r.status)+'</td><td><button class="btn" data-b="'+r.id+'" data-s="confirmed">Confirm</button> <button class="btn" data-b="'+r.id+'" data-s="completed">Complete</button></td></tr>').join('')+'</table>':'<div class="state">No bookings.</div>';$$('[data-b]').forEach(x=>x.onclick=async()=>{await api('/rest/v1/bookings?id=eq.'+x.dataset.b,{method:'PATCH',body:JSON.stringify({status:x.dataset.s})});loadBookings()});loadBuffets()}
async function loadBuffets(){const [b,items]=await Promise.all([api('/rest/v1/booking_bundles?select=*&order=sort_order.asc'),api('/rest/v1/booking_bundle_items?select=*&order=sort_order.asc')]);$('#buffetTable').innerHTML='<table><tr><th>Name</th><th>Price/person</th><th>Contents</th><th>Active</th><th></th></tr>'+b.map(x=>'<tr><td>'+esc(x.name)+'</td><td>UGX '+money(x.price_per_person)+'</td><td>'+items.filter(i=>i.bundle_id===x.id&&i.active).map(i=>esc(i.name)+(i.description?' — '+esc(i.description):'')).join('<br>')+'</td><td>'+x.active+'</td><td><button class="btn" data-buffet="'+x.id+'">Edit</button></td></tr>').join('')+'</table>';$$('[data-buffet]').forEach(x=>x.onclick=()=>editBuffet(x.dataset.buffet))}
async function editBuffet(id){const rows=await api('/rest/v1/booking_bundles?id=eq.'+id);const b=rows[0];const items=await api('/rest/v1/booking_bundle_items?bundle_id=eq.'+id+'&order=sort_order.asc');modal('Edit buffet','<form id="bf" class="form"><input name="name" value="'+esc(b.name)+'" placeholder="Name" required><input name="price" type="number" value="'+b.price_per_person+'" placeholder="Price per person"><textarea name="description" placeholder="Description">'+esc(b.description||'')+'</textarea><label>Active <input name="active" type="checkbox" '+(b.active?'checked':'')+'></label><textarea name="contents" placeholder="One included item per line">'+items.map(i=>i.name+(i.description?' | '+i.description:'')).join('\n')+'</textarea><button class="btn btn-dark">Save</button></form>');$('#bf').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await api('/rest/v1/booking_bundles?id=eq.'+id,{method:'PATCH',body:JSON.stringify({name:f.get('name'),price_per_person:Number(f.get('price')||0),price_on_request:Number(f.get('price')||0)<=0,description:f.get('description'),active:f.get('active')==='on'})});await api('/rest/v1/booking_bundle_items?bundle_id=eq.'+id,{method:'DELETE'});for(const [n,line] of String(f.get('contents')||'').split('\n').map(x=>x.trim()).filter(Boolean).entries()){const [name,...d]=line.split('|');await api('/rest/v1/booking_bundle_items',{method:'POST',body:JSON.stringify({bundle_id:id,name:name.trim(),description:d.join('|').trim()||null,sort_order:n,active:true})})}closeModal();loadBuffets()}}
async function addBuffet(){modal('Add buffet','<form id="bf" class="form"><input name="name" placeholder="Buffet name" required><input name="price" type="number" value="0" placeholder="Price per person"><textarea name="description" placeholder="Description"></textarea><input name="sort" type="number" value="0" placeholder="Sort order"><textarea name="contents" placeholder="One included item per line"></textarea><label>Active <input name="active" type="checkbox" checked></label><button class="btn btn-dark">Save</button></form>');$('#bf').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),r=await api('/rest/v1/booking_bundles',{method:'POST',body:JSON.stringify({name:f.get('name'),price_per_person:Number(f.get('price')||0),price_on_request:Number(f.get('price')||0)<=0,description:f.get('description')||null,sort_order:Number(f.get('sort')||0),active:f.get('active')==='on'})}),id=r?.[0]?.id;if(id)for(const [n,line] of String(f.get('contents')||'').split('\\n').map(x=>x.trim()).filter(Boolean).entries()){const [name,...d]=line.split('|');await api('/rest/v1/booking_bundle_items',{method:'POST',body:JSON.stringify({bundle_id:id,name:name.trim(),description:d.join('|').trim()||null,sort_order:n,active:true})})}closeModal();loadBuffets()}}
async function loadOrders(){const filter=$('#orderStatusFilter').value;let q='/rest/v1/orders?select=*&order=created_at.desc';if(filter==='unpaid')q+='&payment_status=eq.unpaid';else if(filter==='paid')q+='&payment_status=eq.paid';else if(filter==='completed_unpaid')q+='&status=eq.completed&payment_status=eq.unpaid';else if(filter==='completed_paid')q+='&status=eq.completed&payment_status=eq.paid';else if(filter!=='all')q+='&status=eq.'+filter;const rows=await api(q);$('#ordersTable').innerHTML='<table><tr><th>Order</th><th>Status</th><th>Payment</th><th>Total</th><th></th></tr>'+rows.map(r=>'<tr><td>#'+esc(r.id.slice(0,8))+'<br>'+esc(r.source)+'</td><td>'+esc(r.status)+'</td><td>'+esc(r.payment_status)+'</td><td>UGX '+money(r.total)+'</td><td class="actions"><button class="btn" data-paid="'+r.id+'">Mark paid</button> <button class="btn" data-done="'+r.id+'">Complete</button> <button class="btn" data-cancel="'+r.id+'">Cancel</button> <button class="btn" data-items="'+r.id+'">Items</button></td></tr>').join('')+'</table>';$('[data-paid]').forEach(x=>x.onclick=()=>setOrder(x.dataset.paid,null,'paid'));$('[data-done]').forEach(x=>x.onclick=()=>setOrder(x.dataset.done,'completed',null));$('[data-cancel]').forEach(x=>x.onclick=()=>{if(confirm('Cancel this order?'))setOrder(x.dataset.cancel,'cancelled',null)});$('[data-items]').forEach(x=>x.onclick=()=>loadOrderItems(x.dataset.items))}
async function setOrder(id,status,payment){const body={p_order_id:id,p_status:status,p_payment_status:payment};await api('/rest/v1/rpc/admin_set_order_status',{method:'POST',body:JSON.stringify(body)});loadOrders()}
async function loadOrderItems(id){const r=await api('/rest/v1/order_items?select=id,qty,unit_price,item_name_snapshot,notes&order_id=eq.'+id);$('#orderItemsTable').innerHTML='<table><tr><th>Item</th><th>Qty</th><th>Price</th><th>Notes</th></tr>'+r.map(x=>'<tr><td>'+esc(x.item_name_snapshot||'')+'</td><td>'+x.qty+'</td><td>UGX '+money(x.unit_price)+'</td><td>'+esc(x.notes||'')+'</td></tr>').join('')+'</table>'}
async function loadInventory(){const [rows,sm]=await Promise.all([api('/rest/v1/inventory_items?select=*&order=name.asc'),api('/rest/v1/stock_movements?select=item_id,quantity,movement_type')]);const stock={};sm.forEach(x=>stock[x.item_id]=(stock[x.item_id]||0)+(String(x.movement_type).toLowerCase()==='out'?-1:1)*Number(x.quantity||0));$('#inventoryTable').innerHTML='<table><tr><th>Name</th><th>Unit</th><th>Stock</th><th>Reorder</th><th></th></tr>'+rows.map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+esc(x.unit)+'</td><td>'+(stock[x.id]||0)+'</td><td>'+x.reorder_level+'</td><td><button class="btn" data-inv="'+x.id+'">Edit</button></td></tr>').join('')+'</table>';const recipes=await api('/rest/v1/menu_recipes?select=id,menu_item_id,inventory_item_id,quantity,menu_items(name),inventory_items(name,unit)&order=created_at.asc');$('#recipeTable').innerHTML='<div class="toolbar"><button class="btn" id="newRecipe">Add ingredient mapping</button></div>'+(recipes.length?'<table><tr><th>Menu item</th><th>Ingredient</th><th>Quantity</th><th></th></tr>'+recipes.map(r=>'<tr><td>'+esc(r.menu_items?.name||r.menu_item_id)+'</td><td>'+esc(r.inventory_items?.name||r.inventory_item_id)+' ('+esc(r.inventory_items?.unit||'')+')</td><td>'+esc(r.quantity)+'</td><td><button class="btn" data-recipe-edit="'+r.id+'">Edit</button> <button class="btn" data-recipe-delete="'+r.id+'">Delete</button></td></tr>').join('')+'</table>':'<div class="state">No recipe mappings yet.</div>');$('#newRecipe').onclick=manageRecipe;$('[data-recipe-edit]').forEach(x=>x.onclick=()=>editRecipe(x.dataset.recipeEdit));$('[data-recipe-delete]').forEach(x=>x.onclick=async()=>{if(confirm('Delete this recipe mapping?')){await api('/rest/v1/menu_recipes?id=eq.'+x.dataset.recipeDelete,{method:'DELETE'});loadInventory()}});$$('[data-inv]').forEach(x=>x.onclick=()=>editInventory(x.dataset.inv))}
async function editInventory(id=null){const x=id?(await api('/rest/v1/inventory_items?id=eq.'+id))[0]:{name:'',unit:'',category:'',reorder_level:0,active:true};modal(id?'Inventory item':'Add inventory item','<form id="inv" class="form"><input name="name" value="'+esc(x.name)+'" placeholder="Ingredient name" required><input name="unit" value="'+esc(x.unit)+'" placeholder="kg, litre, piece…" required><input name="category" value="'+esc(x.category||'')+'" placeholder="Category"><input name="reorder" type="number" step="0.001" value="'+(x.reorder_level||0)+'" placeholder="Reorder level"><label>Active <input name="active" type="checkbox" '+(x.active?'checked':'')+'></label><button class="btn btn-dark">Save</button></form>');$('#inv').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),body={name:f.get('name'),unit:f.get('unit'),category:f.get('category')||null,reorder_level:Number(f.get('reorder')||0),active:f.get('active')==='on'};await api(id?'/rest/v1/inventory_items?id=eq.'+id:'/rest/v1/inventory_items',{method:id?'PATCH':'POST',body:JSON.stringify(body)});closeModal();loadInventory()}}
async function manageRecipe(existingId=null){const [m,i]=await Promise.all([api('/rest/v1/menu_items?select=id,name&order=name.asc'),api('/rest/v1/inventory_items?select=id,name,unit&active=eq.true&order=name.asc')]);let existing=null;if(existingId)existing=(await api('/rest/v1/menu_recipes?id=eq.'+existingId))[0];modal(existing?'Edit recipe mapping':'Add recipe mapping','<form id="recipe" class="form"><select name="menu">'+m.map(x=>'<option value="'+x.id+'" '+(existing?.menu_item_id===x.id?'selected':'')+'>'+esc(x.name)+'</option>').join('')+'</select><select name="inv">'+i.map(x=>'<option value="'+x.id+'" '+(existing?.inventory_item_id===x.id?'selected':'')+'>'+esc(x.name)+' ('+esc(x.unit)+')</option>').join('')+'</select><input name="qty" type="number" step="0.001" min="0.001" value="'+(existing?.quantity||'')+'" placeholder="Quantity used" required><button class="btn btn-dark">Save</button></form>');$('#recipe').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),body={menu_item_id:f.get('menu'),inventory_item_id:f.get('inv'),quantity:Number(f.get('qty'))};await api(existingId?'/rest/v1/menu_recipes?id=eq.'+existingId:'/rest/v1/menu_recipes',{method:existingId?'PATCH':'POST',body:JSON.stringify(body)});closeModal();loadInventory()}}
async function editRecipe(id){return manageRecipe(id)}
async function loadMenu(){const r=await api('/rest/v1/menu_items?select=*,menu_categories(name)&order=name.asc');$('#menuTable').innerHTML='<table><tr><th>Name</th><th>Category</th><th>Price</th><th>Stock</th><th></th></tr>'+r.map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+esc(x.menu_categories?.name||'')+'</td><td>'+((x.price_on_request)?'Ask':'UGX '+money(x.price))+'</td><td>'+x.in_stock+'</td><td><button class="btn" data-menu="'+x.id+'">Edit</button></td></tr>').join('')+'</table>';$$('[data-menu]').forEach(x=>x.onclick=()=>editMenu(x.dataset.menu))}
async function editMenu(id=null){const cats=await api('/rest/v1/menu_categories?select=id,name&active=eq.true&order=sort_order.asc,name.asc');const x=id?(await api('/rest/v1/menu_items?id=eq.'+id))[0]:{name:'',description:'',price:0,img_url:'',price_on_request:false,in_stock:true,category_id:null};modal(id?'Menu item':'Add menu item','<form id="mi" class="form"><input name="name" value="'+esc(x.name)+'" placeholder="Name" required><select name="category"><option value="">No category</option>'+cats.map(q=>'<option value="'+q.id+'" '+(x.category_id===q.id?'selected':'')+'>'+esc(q.name)+'</option>').join('')+'</select><textarea name="description" placeholder="Description">'+esc(x.description||'')+'</textarea><input name="price" type="number" step="0.01" value="'+(x.price||0)+'" placeholder="Price"><input name="img" value="'+esc(x.img_url||'')+'" placeholder="Image URL"><label>Price on request <input name="por" type="checkbox" '+(x.price_on_request?'checked':'')+'></label><label>In stock <input name="stock" type="checkbox" '+(x.in_stock?'checked':'')+'></label><button class="btn btn-dark">Save</button></form>');$('#mi').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),body={name:f.get('name'),category_id:f.get('category')||null,description:f.get('description')||null,price:Number(f.get('price')||0),img_url:f.get('img')||null,price_on_request:f.get('por')==='on',in_stock:f.get('stock')==='on'};await api(id?'/rest/v1/menu_items?id=eq.'+id:'/rest/v1/menu_items',{method:id?'PATCH':'POST',body:JSON.stringify(body)});closeModal();loadMenu()}}
async function loadServices(){const [s,sp]=await Promise.all([api('/rest/v1/services?select=*&order=name.asc'),api('/rest/v1/sports?select=*&order=name.asc')]);$('#servicesTable').innerHTML='<table><tr><th>Name</th><th>Price</th><th>Pricing</th><th>Active</th><th></th></tr>'+s.map(x=>'<tr><td>'+esc(x.name)+'</td><td>UGX '+money(x.price)+'</td><td>'+esc(x.pricing_mode||'fixed')+'</td><td>'+x.active+'</td><td><button class="btn" data-svc="'+x.id+'">Edit</button></td></tr>').join('')+'</table>';$('#sportsTable').innerHTML='<table><tr><th>Sport</th><th>Description</th><th>Active</th><th></th></tr>'+sp.map(x=>'<tr><td>'+esc(x.name)+'</td><td>'+esc(x.description||'')+'</td><td>'+x.active+'</td><td><button class="btn" data-sport="'+x.id+'">Edit</button></td></tr>').join('')+'</table>';$$('[data-svc]').forEach(x=>x.onclick=()=>editService(x.dataset.svc));$$('[data-sport]').forEach(x=>x.onclick=()=>editSport(x.dataset.sport))}
async function editService(id=null){const x=id?(await api('/rest/v1/services?id=eq.'+id))[0]:{name:'',description:'',price:0,team_threshold:null,small_group_price:null,full_team_price:null,active:true,pricing_mode:'fixed'};modal(id?'Service':'Add service','<form id="svc" class="form"><input name="name" value="'+esc(x.name)+'" placeholder="Service name" required><textarea name="description" placeholder="Description">'+esc(x.description||'')+'</textarea><input name="price" type="number" value="'+(x.price||0)+'" placeholder="Base price"><input name="duration" type="number" value="'+(x.duration_minutes||'')+'" placeholder="Duration minutes"><select name="pricing"><option value="fixed" '+(x.pricing_mode==='fixed'?'selected':'')+'>Fixed</option><option value="per_person" '+(x.pricing_mode==='per_person'?'selected':'')+'>Per person</option><option value="team" '+(x.pricing_mode==='team'?'selected':'')+'>Team</option></select><input name="threshold" type="number" value="'+(x.team_threshold||'')+'" placeholder="Team threshold"><input name="small" type="number" value="'+(x.small_group_price||'')+'" placeholder="Small group price"><input name="full" type="number" value="'+(x.full_team_price||'')+'" placeholder="Full team price"><label>Active <input name="active" type="checkbox" '+(x.active?'checked':'')+'></label><button class="btn btn-dark">Save</button></form>');$('#svc').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),body={name:f.get('name'),description:f.get('description')||null,price:Number(f.get('price')||0),duration_minutes:Number(f.get('duration')||0)||null,pricing_mode:f.get('pricing'),team_threshold:Number(f.get('threshold')||0)||null,small_group_price:Number(f.get('small')||0)||null,full_team_price:Number(f.get('full')||0)||null,active:f.get('active')==='on'};await api(id?'/rest/v1/services?id=eq.'+id:'/rest/v1/services',{method:id?'PATCH':'POST',body:JSON.stringify(body)});closeModal();loadServices()}}
async function editSport(id=null){const x=id?(await api('/rest/v1/sports?id=eq.'+id))[0]:{name:'',description:'',active:true};modal(id?'Sport':'Add sport','<form id="sport" class="form"><input name="name" value="'+esc(x.name)+'" placeholder="Sport name" required><textarea name="description" placeholder="Description">'+esc(x.description||'')+'</textarea><label>Active <input name="active" type="checkbox" '+(x.active?'checked':'')+'></label><button class="btn btn-dark">Save</button></form>');$('#sport').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),body={name:f.get('name'),description:f.get('description')||null,active:f.get('active')==='on'};await api(id?'/rest/v1/sports?id=eq.'+id:'/rest/v1/sports',{method:id?'PATCH':'POST',body:JSON.stringify(body)});closeModal();loadServices()}}
async function loadContent(){const [p,m,a]=await Promise.all([api('/rest/v1/cms_pages?select=*&order=slug.asc'),api('/rest/v1/media?select=*&order=page_slug.asc,sort_order.asc'),api('/rest/v1/announcements?select=*&order=starts_at.desc')]);$('#pagesTable').innerHTML='<table><tr><th>Slug</th><th>Title</th><th>Published</th><th></th></tr>'+p.map(x=>'<tr><td>'+esc(x.slug)+'</td><td>'+esc(x.title||'')+'</td><td>'+x.published+'</td><td><button class="btn" data-page="'+x.id+'">Edit</button></td></tr>').join('')+'</table>';$('#mediaTable').innerHTML='<table><tr><th>Page</th><th>Title</th><th>URL</th><th>Active</th><th></th></tr>'+m.map(x=>'<tr><td>'+esc(x.page_slug||'')+'</td><td>'+esc(x.title||'')+'</td><td>'+esc(x.url)+'</td><td>'+x.active+'</td><td><button class="btn" data-media="'+x.id+'">Edit</button></td></tr>').join('')+'</table>';$('#announcementsTable').innerHTML='<table><tr><th>Title</th><th>Published</th><th>Body</th><th></th></tr>'+a.map(x=>'<tr><td>'+esc(x.title)+'</td><td>'+x.published+'</td><td>'+esc(x.body||'')+'</td><td><button class="btn" data-ann="'+x.id+'">Edit</button></td></tr>').join('')+'</table>';$('[data-page]').forEach(x=>x.onclick=()=>editPage(x.dataset.page));$('[data-media]').forEach(x=>x.onclick=()=>editMedia(x.dataset.media));$('[data-ann]').forEach(x=>x.onclick=()=>editAnnouncement(x.dataset.ann))}
function table(h,rows,fn){return '<table><tr>'+h.map(x=>'<th>'+x+'</th>').join('')+'</tr>'+rows.map(x=>'<tr>'+fn(x).map(v=>'<td>'+((typeof v==='string'&&v.trim().startsWith('<button'))?v:esc(v))+'</td>').join('')+'</tr>').join('')+'</table>'}
async function editPage(id){const x=(await api('/rest/v1/cms_pages?id=eq.'+id))[0];modal('CMS page','<form id="ed" class="form"><input name="title" value="'+esc(x.title||'')+'"><textarea name="content">'+esc(JSON.stringify(x.content||{},null,2))+'</textarea><label>Published <input name="published" type="checkbox" '+(x.published?'checked':'')+'></label><button class="btn btn-dark">Save</button></form>');$('#ed').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);let content={};try{content=JSON.parse(f.get('content')||'{}')}catch{alert('Content must be valid JSON');return}await api('/rest/v1/cms_pages?id=eq.'+id,{method:'PATCH',body:JSON.stringify({title:f.get('title'),content,published:f.get('published')==='on',updated_at:new Date().toISOString()})});closeModal();loadContent()}}
async function editMedia(id){const x=(await api('/rest/v1/media?id=eq.'+id))[0];modal('Media','<form id="ed" class="form"><input name="title" value="'+esc(x.title||'')+'"><input name="url" value="'+esc(x.url)+'" required><input name="alt" value="'+esc(x.alt_text||'')+'"><input name="page" value="'+esc(x.page_slug||'')+'"><input name="sort" type="number" value="'+x.sort_order+'"><label>Active <input name="active" type="checkbox" '+(x.active?'checked':'')+'></label><button class="btn btn-dark">Save</button></form>');$('#ed').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await api('/rest/v1/media?id=eq.'+id,{method:'PATCH',body:JSON.stringify({title:f.get('title'),url:f.get('url'),alt_text:f.get('alt'),page_slug:f.get('page'),sort_order:Number(f.get('sort')||0),active:f.get('active')==='on'})});closeModal();loadContent()}}
async function editAnnouncement(id){const x=(await api('/rest/v1/announcements?id=eq.'+id))[0];modal('Announcement','<form id="ed" class="form"><input name="title" value="'+esc(x.title)+'" required><textarea name="body">'+esc(x.body||'')+'</textarea><label>Published <input name="published" type="checkbox" '+(x.published?'checked':'')+'></label><button class="btn btn-dark">Save</button></form>');$('#ed').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await api('/rest/v1/announcements?id=eq.'+id,{method:'PATCH',body:JSON.stringify({title:f.get('title'),body:f.get('body'),published:f.get('published')==='on'})});closeModal();loadContent()}}
async function addMedia(){modal('Add media','<form id="mediaForm" class="form"><input name="title" placeholder="Title"><input name="url" placeholder="Image/video URL" required><input name="alt" placeholder="Alt text"><input name="page" placeholder="Page slug"><input name="area" placeholder="Area (e.g. gallery)" value="gallery" required><input name="type" placeholder="Type" value="image"><input name="sort" type="number" value="0"><label>Gallery item <input name="gallery" type="checkbox" checked></label><label>Active <input name="active" type="checkbox" checked></label><button class="btn btn-dark">Save</button></form>');$('#mediaForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await api('/rest/v1/media',{method:'POST',body:JSON.stringify({title:f.get('title')||null,url:f.get('url'),alt_text:f.get('alt')||null,page_slug:f.get('page')||null,area:f.get('area'),type:f.get('type')||null,sort_order:Number(f.get('sort')||0),is_gallery:f.get('gallery')==='on',active:f.get('active')==='on'})});closeModal();loadContent()}}
async function addAnnouncement(){modal('Add announcement','<form id="annForm" class="form"><input name="title" placeholder="Title" required><textarea name="body" placeholder="Message"></textarea><input name="starts" type="datetime-local"><input name="ends" type="datetime-local"><label>Published <input name="published" type="checkbox"></label><button class="btn btn-dark">Save</button></form>');$('#annForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await api('/rest/v1/announcements',{method:'POST',body:JSON.stringify({title:f.get('title'),body:f.get('body')||null,starts_at:f.get('starts')?new Date(f.get('starts')).toISOString():null,ends_at:f.get('ends')?new Date(f.get('ends')).toISOString():null,published:f.get('published')==='on'})});closeModal();loadContent()}}
async function loadReviews(){const r=await api('/rest/v1/reviews?select=*&order=created_at.desc');$('#reviewsTable').innerHTML=table(['Name','Rating','Message','Approved',''],r,x=>[x.customer_name,x.rating,x.message,x.approved,'<button class="btn" data-rm="'+x.id+'">Remove</button>']);$$('[data-rm]').forEach(x=>x.onclick=async()=>{if(confirm('Remove this review?')){await api('/rest/v1/reviews?id=eq.'+x.dataset.rm,{method:'DELETE'});loadReviews()}})}
async function loadSocial(){const r=await api('/rest/v1/social_links?select=*&order=sort_order.asc');$('#socialTable').innerHTML=table(['Platform','Label','URL','Active',''],r,x=>[x.platform,x.label,x.url,x.active,'<button class="btn" data-sl="'+x.id+'">Edit</button>']);$$('[data-sl]').forEach(x=>x.onclick=()=>editSocial(x.dataset.sl))}
async function editSocial(id){const x=id?(await api('/rest/v1/social_links?id=eq.'+id))[0]:{platform:'',label:'',url:'',sort_order:0,active:true};modal('Social link','<form id="sl" class="form"><input name="platform" value="'+esc(x.platform)+'" placeholder="Platform"><input name="label" value="'+esc(x.label)+'" placeholder="Label"><input name="url" type="url" value="'+esc(x.url)+'" placeholder="https://..." required><input name="sort" type="number" value="'+x.sort_order+'"><label>Active <input name="active" type="checkbox" '+(x.active?'checked':'')+'></label><button class="btn btn-dark">Save</button></form>');$('#sl').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const body={platform:f.get('platform'),label:f.get('label'),url:f.get('url'),sort_order:Number(f.get('sort')||0),active:f.get('active')==='on'};await api(id?'/rest/v1/social_links?id=eq.'+id:'/rest/v1/social_links',{method:id?'PATCH':'POST',body:JSON.stringify(body)});closeModal();loadSocial()}}
async function loadTeamPositions(){const rows=await api('/rest/v1/team_positions?select=id,department,position,person_name,sort_order,active&order=sort_order.asc');$('#teamPositionsTable').innerHTML='<table><tr><th>Department</th><th>Position</th><th>Person</th><th>Active</th><th></th></tr>'+rows.map(x=>'<tr><td>'+esc(x.department)+'</td><td>'+esc(x.position)+'</td><td>'+esc(x.person_name||'')+'</td><td>'+x.active+'</td><td><button class="btn" data-team-edit="'+x.id+'">Edit</button> <button class="btn" data-team-delete="'+x.id+'">Remove</button></td></tr>').join('')+'</table>';$$('[data-team-edit]').forEach(x=>x.onclick=()=>editTeamPosition(x.dataset.teamEdit));$$('[data-team-delete]').forEach(x=>x.onclick=()=>deleteTeamPosition(x.dataset.teamDelete))}
function editTeamPosition(id){const load=id?api('/rest/v1/team_positions?id=eq.'+id):Promise.resolve([{department:'',position:'',person_name:'',sort_order:100,active:true}]);load.then(rows=>{const x=rows[0];modal(id?'Edit position':'Add position','<form id="teamPositionForm" class="form"><input name="department" required placeholder="Department" value="'+esc(x.department||'')+'"><input name="position" required placeholder="Position" value="'+esc(x.position||'')+'"><input name="person_name" placeholder="Person’s name" value="'+esc(x.person_name||'')+'"><input name="sort_order" type="number" value="'+Number(x.sort_order||100)+'"><label>Active <input name="active" type="checkbox" '+(x.active?'checked':'')+'></label><button class="btn btn-dark" type="submit">Save</button></form>');$('#teamPositionForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const body={department:String(f.get('department')||'').trim(),position:String(f.get('position')||'').trim(),person_name:String(f.get('person_name')||'').trim(),sort_order:Number(f.get('sort_order')||100),active:f.get('active')==='on',updated_at:new Date().toISOString()};await api(id?'/rest/v1/team_positions?id=eq.'+id:'/rest/v1/team_positions',{method:id?'PATCH':'POST',body:JSON.stringify(body)});closeModal();loadTeamPositions()}})}
async function deleteTeamPosition(id){if(!confirm('Remove this public position?'))return;await api('/rest/v1/team_positions?id=eq.'+id,{method:'DELETE'});loadTeamPositions()}
async function addStaff(){const roles=await api('/rest/v1/roles?select=id,name&order=name.asc');const usable=roles.filter(r=>r.name!=='owner');modal('Add staff','<form id="newStaffForm" class="form"><input name="name" placeholder="Full name" required><input name="email" type="email" placeholder="Email address" required><input name="phone" placeholder="Phone"><select name="role" required><option value="">Choose role</option>'+usable.map(r=>'<option value="'+esc(r.name)+'">'+esc(r.name)+'</option>').join('')+'</select><p class="muted">The staff member will receive an invitation and set their own password.</p><button class="btn btn-dark">Send invitation</button></form>');$('#newStaffForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/functions/v1/invite-staff',{method:'POST',body:JSON.stringify({name:String(f.get('name')||'').trim(),email:String(f.get('email')||'').trim(),phone:String(f.get('phone')||'').trim(),role:String(f.get('role')||'').trim()})});alert('Invitation sent.');closeModal();loadStaff()}catch(err){alert(err.message||'Could not send invitation.')}}}
async function loadStaff(){await loadTeamPositions();const [r,roles]=await Promise.all([api('/rest/v1/profiles?select=id,full_name,phone,role,active,created_at&order=full_name.asc'),api('/rest/v1/roles?select=id,name&order=name.asc')]);$('#staffTable').innerHTML='<table><tr><th>Name</th><th>Phone</th><th>Role</th><th>Active</th><th></th></tr>'+r.map(x=>'<tr><td>'+esc(x.full_name)+'</td><td>'+esc(x.phone||'')+'</td><td>'+esc(x.role)+'</td><td>'+x.active+'</td><td><button class="btn" data-staff="'+x.id+'">Edit</button></td></tr>').join('')+'</table>';$('[data-staff]').forEach(x=>x.onclick=()=>editStaff(x.dataset.staff,roles))}
async function editStaff(id,roles){const x=(await api('/rest/v1/profiles?id=eq.'+id))[0];modal('Staff profile','<form id="staffForm" class="form"><input name="name" value="'+esc(x.full_name||'')+'"><input name="phone" value="'+esc(x.phone||'')+'"><select name="role">'+roles.map(r=>'<option '+(r.name===x.role?'selected':'')+' value="'+esc(r.name)+'">'+esc(r.name)+'</option>').join('')+'</select><label>Active <input name="active" type="checkbox" '+(x.active?'checked':'')+'></label><button class="btn btn-dark">Save</button></form>');$('#staffForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await api('/rest/v1/profiles?id=eq.'+id,{method:'PATCH',body:JSON.stringify({full_name:f.get('name'),phone:f.get('phone'),role:f.get('role'),active:f.get('active')==='on'})});closeModal();loadStaff()}}
async function loadReport(){const from=$('#reportFrom').value||today(),to=$('#reportTo').value||today();const [b,o,e]=await Promise.all([api('/rest/v1/bookings?select=id,total,booking_date&booking_date=gte.'+from+'&booking_date=lte.'+to),api('/rest/v1/orders?select=id,total,created_at&created_at=gte.'+from+'T00:00:00&created_at=lte.'+to+'T23:59:59'),api('/rest/v1/events?select=id,total&event_date=gte.'+from+'&event_date=lte.'+to)]);$('#reportBookings').textContent=b.length;$('#reportOrders').textContent=o.length;$('#reportEvents').textContent=e.length;$('#reportRevenue').textContent='UGX '+money(b.reduce((a,x)=>a+Number(x.total||0),0)+o.reduce((a,x)=>a+Number(x.total||0),0)+e.reduce((a,x)=>a+Number(x.total||0),0));$('#reportTable').innerHTML=table(['Type','ID','Value'],[...b.map(x=>['Booking',x.id,x.total]),...o.map(x=>['Order',x.id,x.total]),...e.map(x=>['Event',x.id,x.total])],x=>x)}
async function loadSettings(){const r=await api('/rest/v1/site_settings?select=key,value&order=key.asc');$('#settingsTable').innerHTML=r.map(x=>'<label>'+esc(x.key)+'<input data-set="'+esc(x.key)+'" value="'+esc(x.value||'')+'"></label>').join('')}
async function saveSettings(){for(const x of $$('[data-set]'))await api('/rest/v1/site_settings?key=eq.'+encodeURIComponent(x.dataset.set),{method:'PATCH',body:JSON.stringify({value:x.value,updated_at:new Date().toISOString()})});loadSettings()}
function modal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.add('open')}
function closeModal(){$('#modal').classList.remove('open');$('#modalBody').innerHTML=''}
$('#loginForm').addEventListener('submit',login);$('#logout').onclick=async()=>{try{await api('/auth/v1/logout',{method:'POST'})}catch{}sessionStorage.removeItem('kiteezi_admin_session');location.reload()};$('#nav').addEventListener('click',e=>{const a=e.target.closest('[data-tab]');if(a){e.preventDefault();history.replaceState(null,'','#'+a.dataset.tab);route(a.dataset.tab)}});window.addEventListener('hashchange',()=>route(location.hash.slice(1)));$('#modalClose').onclick=closeModal;$('#refreshBookings').onclick=loadBookings;$('#refreshOrders').onclick=loadOrders;$('#refreshInventory').onclick=loadInventory;$('#refreshMenu').onclick=loadMenu;$('#refreshServices').onclick=loadServices;$('#refreshPages').onclick=loadContent;$('#refreshMedia').onclick=loadContent;$('#refreshAnnouncements').onclick=loadContent;$('#refreshReviews').onclick=loadReviews;$('#refreshSocial').onclick=loadSocial;$('#newStaff').onclick=addStaff;$('#refreshStaff').onclick=loadStaff;$('#newTeamPosition').onclick=()=>editTeamPosition();$('#generateReport').onclick=loadReport;$('#refreshSettings').onclick=loadSettings;$('#saveSettings').onclick=saveSettings;$('#newOrder').onclick=async()=>{const m=await api('/rest/v1/menu_items?select=id,name,price,price_on_request,in_stock&in_stock=eq.true&price_on_request=eq.false&order=name.asc');modal('New POS order','<form id="pos" class="form"><input name="customer" placeholder="Customer name"><input name="phone" placeholder="Phone"><textarea name="notes" placeholder="Notes"></textarea><div id="posItems">'+m.map(x=>'<label style="display:flex;gap:8px;align-items:center"><input type="number" min="0" value="0" data-pos="'+x.id+'" style="width:80px"><span>'+esc(x.name)+' — UGX '+money(x.price)+'</span></label>').join('')+'</div><button class="btn btn-dark">Create order</button></form>');$('#pos').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),items=[...e.currentTarget.querySelectorAll('[data-pos]')].map(x=>({id:x.dataset.pos,quantity:Number(x.value||0)})).filter(x=>x.quantity>0);if(!items.length)return alert('Select at least one item.');await api('/rest/v1/rpc/create_pos_order',{method:'POST',body:JSON.stringify({p_customer_name:f.get('customer')||null,p_phone:f.get('phone')||null,p_items:items,p_notes:f.get('notes')||null})});closeModal();loadOrders()}};$('#newSocial').onclick=()=>editSocial();$('#newInventoryItem').onclick=()=>editInventory();$('#inventorySearch').oninput=e=>{const q=e.target.value.toLowerCase();$('#inventoryTable tbody tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')};$('#newMenu').onclick=()=>editMenu();$('#newService').onclick=()=>editService();$('#newSport').onclick=()=>editSport();$('#newMedia').onclick=addMedia;$('#newAnnouncement').onclick=addAnnouncement;$('#newBuffet').onclick=addBuffet;restore();