alter table public.booking_bundles add column if not exists pricing_mode text not null default 'per_person', add column if not exists serves_people integer;
alter table public.booking_bundle_items add column if not exists component_area text, add column if not exists selection_mode text not null default 'fixed', add column if not exists min_select integer not null default 0, add column if not exists max_select integer not null default 0, add column if not exists item_quantity integer not null default 1;
alter table public.booking_components drop constraint if exists booking_components_component_type_check;
alter table public.booking_components add constraint booking_components_component_type_check check (component_type = any(array['service','menu_item','buffet','buffet_option']));
alter table public.booking_bundles drop constraint if exists booking_bundles_pricing_mode_check;
alter table public.booking_bundles add constraint booking_bundles_pricing_mode_check check (pricing_mode in ('per_person','fixed_package'));
alter table public.booking_bundles drop constraint if exists booking_bundles_serves_people_check;
alter table public.booking_bundles add constraint booking_bundles_serves_people_check check (serves_people is null or serves_people > 0);
alter table public.booking_bundle_items drop constraint if exists booking_bundle_items_selection_mode_check;
alter table public.booking_bundle_items add constraint booking_bundle_items_selection_mode_check check (selection_mode in ('fixed','choose'));
alter table public.booking_bundle_items drop constraint if exists booking_bundle_items_min_select_check;
alter table public.booking_bundle_items add constraint booking_bundle_items_min_select_check check (min_select >= 0);
alter table public.booking_bundle_items drop constraint if exists booking_bundle_items_max_select_check;
alter table public.booking_bundle_items add constraint booking_bundle_items_max_select_check check (max_select >= min_select);
alter table public.booking_bundle_items drop constraint if exists booking_bundle_items_item_quantity_check;
alter table public.booking_bundle_items add constraint booking_bundle_items_item_quantity_check check (item_quantity > 0);
create index if not exists idx_booking_bundle_items_bundle_area on public.booking_bundle_items(bundle_id,component_area,sort_order);
update public.booking_bundles set pricing_mode='per_person',serves_people=null where name in ('Ordinary Buffet','Standard Buffet','Ethnic Buffet');
update public.booking_bundles set name='Buffet — 45,000 UGX',pricing_mode='per_person',serves_people=null,description='Starters, stew, extra sauce, grills, food, green vegetables and additions. Component choices are enforced below.' where name='Standard Buffet';
update public.booking_bundles set name='Muchomo Platter',pricing_mode='fixed_package',serves_people=4,price_per_person=55000,description='Fixed platter serving 4 people: 2 sausages, goat, liver, chicken, fish fingers, chapatti, chips and salads.' where name='Muchomo Platter (4 People)';
delete from public.booking_bundle_items;
with b as (select id,name from public.booking_bundles)
insert into public.booking_bundle_items(bundle_id,name,component_area,selection_mode,min_select,max_select,item_quantity,sort_order,active)
select b.id,v.name,v.area,v.mode,v.min_select,v.max_select,v.qty,v.sort_order,true
from b join (values
('Ordinary Buffet','Beef stew','Stew','fixed',0,0,1,1),('Ordinary Buffet','Groundnuts (G. Nuts)','Extra Sauce','choose',1,1,1,2),('Ordinary Buffet','Beans','Extra Sauce','choose',1,1,1,3),('Ordinary Buffet','Peas','Extra Sauce','choose',1,1,1,4),('Ordinary Buffet','Chicken','Grills','choose',1,1,1,5),('Ordinary Buffet','Fish','Grills','choose',1,1,1,6),('Ordinary Buffet','Goat','Grills','choose',1,1,1,7),('Ordinary Buffet','Matooke','Food','fixed',0,0,1,8),('Ordinary Buffet','Posho','Food','fixed',0,0,1,9),('Ordinary Buffet','Sweet Potatoes','Food','fixed',0,0,1,10),('Ordinary Buffet','Cassava','Food','fixed',0,0,1,11),('Ordinary Buffet','Pumpkin','Food','fixed',0,0,1,12),('Ordinary Buffet','Vegetable Rice','Rice','choose',1,1,1,13),('Ordinary Buffet','Brown Rice','Rice','choose',1,1,1,14),('Ordinary Buffet','Plain Rice','Rice','choose',1,1,1,15),('Ordinary Buffet','Nakati','Greens','fixed',0,0,1,16),('Ordinary Buffet','Spinach','Greens','fixed',0,0,1,17),('Ordinary Buffet','Bugga','Greens','fixed',0,0,1,18),('Ordinary Buffet','Soda','Drinks','choose',1,1,1,19),('Ordinary Buffet','Water','Drinks','choose',1,1,1,20),('Ordinary Buffet','Pineapple','Fruit Salad','fixed',0,0,1,21),('Ordinary Buffet','Watermelon','Fruit Salad','fixed',0,0,1,22),
('Buffet — 45,000 UGX','Vegetable salad','Starters','fixed',0,0,1,1),('Buffet — 45,000 UGX','Beef','Stew','choose',1,1,1,2),('Buffet — 45,000 UGX','Goat','Stew','choose',1,1,1,3),('Buffet — 45,000 UGX','Groundnuts','Extra Sauce','choose',1,1,1,4),('Buffet — 45,000 UGX','Beans','Extra Sauce','choose',1,1,1,5),('Buffet — 45,000 UGX','Cow peas','Extra Sauce','choose',1,1,1,6),('Buffet — 45,000 UGX','Beef','Grills','choose',2,2,1,7),('Buffet — 45,000 UGX','Fish fingers','Grills','choose',2,2,1,8),('Buffet — 45,000 UGX','Chicken','Grills','choose',2,2,1,9),('Buffet — 45,000 UGX','Fish','Grills','choose',2,2,1,10),('Buffet — 45,000 UGX','Goat','Grills','choose',2,2,1,11),('Buffet — 45,000 UGX','Matooke','Food','fixed',0,0,1,12),('Buffet — 45,000 UGX','Rice','Food','fixed',0,0,1,13),('Buffet — 45,000 UGX','Posho','Food','fixed',0,0,1,14),('Buffet — 45,000 UGX','Pumpkin','Food','fixed',0,0,1,15),('Buffet — 45,000 UGX','Irish','Food','fixed',0,0,1,16),('Buffet — 45,000 UGX','Nakati','Green Vegetables','choose',1,1,1,17),('Buffet — 45,000 UGX','Dodo','Green Vegetables','choose',1,1,1,18),('Buffet — 45,000 UGX','Bugga','Green Vegetables','choose',1,1,1,19),('Buffet — 45,000 UGX','Spaghetti','Additions','fixed',0,0,1,20),
('Ethnic Buffet','Coleslaw','Starters','fixed',0,0,1,1),('Ethnic Buffet','Vegetable salad','Starters','fixed',0,0,1,2),('Ethnic Buffet','Mushroom','Soups','choose',1,1,1,3),('Ethnic Buffet','Pumpkin','Soups','choose',1,1,1,4),('Ethnic Buffet','Beef','Stews','choose',1,1,1,5),('Ethnic Buffet','Goat','Stews','choose',1,1,1,6),('Ethnic Buffet','Groundnuts with Fish','Luwombo','choose',1,1,1,7),('Ethnic Buffet','Groundnuts with Beef','Luwombo','choose',1,1,1,8),('Ethnic Buffet','Groundnuts with Mushrooms','Luwombo','choose',1,1,1,9),('Ethnic Buffet','Chicken Luwombo','Luwombo','choose',1,1,1,10),('Ethnic Buffet','Groundnuts','Extra Sauce','choose',1,1,1,11),('Ethnic Buffet','Beans','Extra Sauce','choose',1,1,1,12),('Ethnic Buffet','Cow peas','Extra Sauce','choose',1,1,1,13),('Ethnic Buffet','Beef','Grills','choose',1,1,1,14),('Ethnic Buffet','Fish fingers','Grills','choose',1,1,1,15),('Ethnic Buffet','Chicken','Grills','choose',1,1,1,16),('Ethnic Buffet','Fish','Grills','choose',1,1,1,17),('Ethnic Buffet','Goat','Grills','choose',1,1,1,18),('Ethnic Buffet','Matooke','Food','fixed',0,0,1,19),('Ethnic Buffet','Kalo','Food','fixed',0,0,1,20),('Ethnic Buffet','Posho','Food','fixed',0,0,1,21),('Ethnic Buffet','Sweet Potatoes','Food','fixed',0,0,1,22),('Ethnic Buffet','Cassava','Food','fixed',0,0,1,23),('Ethnic Buffet','Pumpkin','Food','fixed',0,0,1,24),('Ethnic Buffet','Vegetable Rice','Rice','choose',1,1,1,25),('Ethnic Buffet','Brown Rice','Rice','choose',1,1,1,26),('Ethnic Buffet','Mixed vegetables: French beans, Carrots, Cauliflower','Greens','fixed',0,0,1,27),('Ethnic Buffet','Nakati','Greens','fixed',0,0,1,28),('Ethnic Buffet','Spinach','Greens','fixed',0,0,1,29),('Ethnic Buffet','Bugga','Greens','fixed',0,0,1,30),('Ethnic Buffet','Bottle of water','Drinks','choose',1,1,1,31),('Ethnic Buffet','Soda','Drinks','choose',1,1,1,32),('Ethnic Buffet','Spaghetti','Additions','fixed',0,0,1,33),('Ethnic Buffet','Fruit salad','Desserts','fixed',0,0,1,34),('Ethnic Buffet','Cake','Desserts','fixed',0,0,1,35),('Ethnic Buffet','Eshabwe','Traditional','choose',1,1,1,36),('Ethnic Buffet','Malewa','Traditional','choose',1,1,1,37),
('Muchomo Platter','Sausages','Platter','fixed',0,0,2,1),('Muchomo Platter','Goat','Platter','fixed',0,0,1,2),('Muchomo Platter','Liver','Platter','fixed',0,0,1,3),('Muchomo Platter','Chicken','Platter','fixed',0,0,1,4),('Muchomo Platter','Fish fingers','Platter','fixed',0,0,1,5),('Muchomo Platter','Chapatti','Platter','fixed',0,0,1,6),('Muchomo Platter','Chips','Platter','fixed',0,0,1,7),('Muchomo Platter','Salads','Platter','fixed',0,0,1,8)
) as v(bundle_name,name,area,mode,min_select,max_select,qty,sort_order) on v.bundle_name=b.name;

create or replace function public.calculate_booking_component_price(p_component_type text,p_source_id uuid,p_quantity integer)
returns table(name_snapshot text,description_snapshot text,unit_price numeric,line_total numeric,price_on_request boolean,service_id uuid,menu_item_id uuid,reference_key text)
language plpgsql stable set search_path=public as $$ declare s public.services%rowtype;m public.menu_items%rowtype;b public.booking_bundles%rowtype;q integer; begin
if coalesce(p_quantity,0)<=0 then raise exception 'Quantity must be greater than zero'; end if;
if p_component_type='service' then select * into s from public.services where id=p_source_id and active=true;if not found then raise exception 'Service is unavailable';end if;q:=case when s.pricing_mode in('per_person','per_person_team') then p_quantity else 1 end;unit_price:=case when s.pricing_mode='per_person_team' and s.team_threshold is not null then case when q<s.team_threshold then coalesce(s.small_group_price,s.price,0) else coalesce(s.full_team_price,s.price,0) end else coalesce(s.price,0) end;name_snapshot:=s.name;description_snapshot:=s.description;price_on_request:=unit_price=0 and s.price is null;service_id:=s.id;menu_item_id:=null;reference_key:=null;line_total:=case when price_on_request then 0 else unit_price*q end;return next;
elsif p_component_type='menu_item' then select * into m from public.menu_items where id=p_source_id and in_stock=true;if not found then raise exception 'Menu item is unavailable';end if;name_snapshot:=m.name;description_snapshot:=m.description;unit_price:=coalesce(m.price,0);price_on_request:=coalesce(m.price_on_request,false) or unit_price=0;service_id:=null;menu_item_id:=m.id;reference_key:=null;line_total:=case when price_on_request then 0 else unit_price*p_quantity end;return next;
elsif p_component_type='buffet' then select * into b from public.booking_bundles where id=p_source_id and active=true;if not found then raise exception 'Buffet package is unavailable';end if;name_snapshot:=b.name;description_snapshot:=b.description;unit_price:=coalesce(b.price_per_person,0);price_on_request:=coalesce(b.price_on_request,false) or unit_price=0;service_id:=null;menu_item_id:=null;reference_key:=b.id::text;line_total:=case when price_on_request then 0 when b.pricing_mode='fixed_package' then unit_price*greatest(1,ceil(p_quantity::numeric/coalesce(b.serves_people,1))::integer) else unit_price*p_quantity end;return next;
else raise exception 'Unsupported booking component type';end if;end $$;

create or replace function public.submit_public_booking_v3(p_customer_name text,p_phone text,p_email text,p_booking_date date,p_start_time time,p_people integer,p_notes text,p_components jsonb)
returns jsonb language plpgsql security definer set search_path=public,private,pg_catalog,pg_temp as $$
declare v_customer_id uuid;v_booking_id uuid;v_primary_service uuid;v_service_category text;v_total numeric:=0;v_on_request boolean:=false;v_has_catering boolean:=false;c jsonb;r record;v_qty integer;v_bundle record;v_opt jsonb;v_count integer;v_fixed record;v_selected_ids uuid[];
begin
if coalesce(trim(p_customer_name),'')='' then raise exception 'Customer name is required';end if;if p_booking_date is null then raise exception 'Booking date is required';end if;if p_booking_date<current_date then raise exception 'Booking date cannot be in the past';end if;if p_people is null or p_people<1 then raise exception 'People must be at least 1';end if;if jsonb_typeof(coalesce(p_components,'[]'::jsonb))<>'array' or jsonb_array_length(coalesce(p_components,'[]'::jsonb))=0 then raise exception 'Select at least one service or booking item';end if;
select c.id into v_customer_id from public.customers c where c.phone=private.normalize_phone(p_phone) limit 1;if v_customer_id is null then insert into public.customers(name,phone,email) values(trim(p_customer_name),private.normalize_phone(p_phone),nullif(trim(p_email),'')) returning id into v_customer_id;else update public.customers set name=trim(p_customer_name),email=coalesce(nullif(trim(p_email),''),email) where id=v_customer_id;end if;
insert into public.bookings(customer_id,service_id,booking_date,start_time,people,source,status,payment_status,total,total_on_request,notes) values(v_customer_id,null,p_booking_date,p_start_time,p_people,'website','pending','unpaid',0,false,nullif(trim(p_notes),'')) returning id into v_booking_id;
for c in select value from jsonb_array_elements(p_components) loop
if lower(coalesce(c->>'type','')) not in('service','menu_item','buffet') then raise exception 'Unsupported booking component type';end if;v_qty:=greatest(1,coalesce((c->>'quantity')::integer,p_people));select * into r from public.calculate_booking_component_price(lower(c->>'type'),(c->>'id')::uuid,v_qty);
insert into public.booking_components(booking_id,component_type,service_id,menu_item_id,reference_key,name_snapshot,description_snapshot,unit_price,quantity,price_on_request,bundle_id) values(v_booking_id,lower(c->>'type'),r.service_id,r.menu_item_id,r.reference_key,r.name_snapshot,r.description_snapshot,r.unit_price,v_qty,r.price_on_request,case when lower(c->>'type')='buffet' then (c->>'id')::uuid else null end);
if v_primary_service is null and r.service_id is not null then v_primary_service:=r.service_id;end if;if lower(c->>'type') in('menu_item','buffet') then v_has_catering:=true;end if;v_total:=v_total+coalesce(r.line_total,0);v_on_request:=v_on_request or r.price_on_request;
if lower(c->>'type')='buffet' then
select * into v_bundle from public.booking_bundles where id=(c->>'id')::uuid and active=true;if not found then raise exception 'Buffet package is unavailable';end if;
select array_agg((x->>'id')::uuid) into v_selected_ids from jsonb_array_elements(coalesce(c->'options','[]'::jsonb)) x where x ? 'id';
for v_fixed in select * from public.booking_bundle_items where bundle_id=v_bundle.id and active=true and selection_mode='fixed' order by sort_order loop insert into public.booking_components(booking_id,component_type,reference_key,name_snapshot,description_snapshot,unit_price,quantity,price_on_request,bundle_id) values(v_booking_id,'buffet_option',v_fixed.id::text,v_fixed.name,v_fixed.description,0,v_fixed.item_quantity,false,v_bundle.id);end loop;
for v_fixed in select distinct component_area,min(min_select) min_select,max(max_select) max_select from public.booking_bundle_items where bundle_id=v_bundle.id and active=true and selection_mode='choose' group by component_area loop
select count(*) into v_count from public.booking_bundle_items bi where bi.bundle_id=v_bundle.id and bi.component_area=v_fixed.component_area and bi.active=true and bi.selection_mode='choose' and bi.id=any(coalesce(v_selected_ids,array[]::uuid[]));if v_count<v_fixed.min_select or v_count>v_fixed.max_select then raise exception '%: choose between % and % option(s)',v_fixed.component_area,v_fixed.min_select,v_fixed.max_select;end if;end loop;
for v_opt in select value from jsonb_array_elements(coalesce(c->'options','[]'::jsonb)) loop select * into v_fixed from public.booking_bundle_items where id=(v_opt->>'id')::uuid and bundle_id=v_bundle.id and active=true and selection_mode='choose';if not found then raise exception 'Invalid buffet option for %',v_bundle.name;end if;insert into public.booking_components(booking_id,component_type,reference_key,name_snapshot,description_snapshot,unit_price,quantity,price_on_request,bundle_id) values(v_booking_id,'buffet_option',v_fixed.id::text,v_fixed.name,v_fixed.description,0,v_fixed.item_quantity,false,v_bundle.id);end loop;
end if;end loop;
select lower(coalesce(category,'')) into v_service_category from public.services where id=v_primary_service;if v_service_category is null then raise exception 'A valid primary service is required';end if;if v_service_category not in('sports','swimming') and not v_has_catering then raise exception 'Catering is required for this booking type. Please select a buffet or menu item.';end if;update public.bookings set service_id=v_primary_service,total=v_total,total_on_request=v_on_request where id=v_booking_id;return jsonb_build_object('booking_id',v_booking_id,'customer_id',v_customer_id,'total',v_total,'total_on_request',v_on_request);end $$;